---
title: "Air quality warnings"

listing:
  - id: aq-warnings
    template: _aqw_listing.ejs
    contents:
      - ./_recent_warnings.yaml
    sort: "date desc"
---

## Issued warnings

::: {#aq-warnings}
:::

## Latest updates

{{< callout_start >}}

**For the latest updates**:

- Subscribe to the [Air Quality Subscription Service](https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/air-advisories/air-quality-subscription-service)
- Outside regular business hours, visit [Environment and Climate Change Canada’s Public Weather Alerts for B.C.](https://weather.gc.ca/?province=bc&zoom=5&alertTableFilterProv=BC)
- For information about air quality warnings within [**Metro Vancouver** and parts of the **Fraser Valley Regional District**](https://gis.metrovancouver.org/maps/Air), visit [Metro Vancouver’s Air Quality Data and Warnings](https://metrovancouver.org/services/air-quality-climate-action/air-quality-data-and-advisories) webpage.

{{< callout_end >}}


## About air quality warnings

An air quality warning is issued when pollutant concentrations approach or exceed predetermined limits, or when degraded-air-quality episodes are expected to continue or worsen.

Warnings are issued to:

- inform about degraded air quality
- help people make informed choices about reducing their exposure to elevated concentrations of air pollutants
- provide vulnerable individuals and the general public with health advice developed by BC health agencies

Warnings, other than those driven by wildfire smoke, serve as a trigger for emission reduction actions (such as industrial emissions or wood stove use) when specified by provincial waste discharge authorizations and local government bylaws.
